### ISSUE TITLE
Action view date sidebar: show days, week, month 

### ISSUE THREAD

**Issue by Exr0n** [Shabang-Systems/cao#1]
maybe with a settings page?? that allows you to customize it? i don't think having the +/- buttons inline makes that much sense

**Comment by Jemoka** [comment]
true but building settings page is very hard

**Comment by Jemoka** [comment]
settings view closed by https://github.com/Shabang-Systems/cao/commit/6039a43c5fa2a98a5537c16cf99a789c927de9c5;  if you want anything else open a new one.
