### ISSUE TITLE
Action view: on-hover "complete" checkmark action button without having to click into the task 

### ISSUE THREAD

**Issue by Exr0n** [Shabang-Systems/cao#4]
<img width="222" alt="image" src="https://github.com/user-attachments/assets/2122556a-0f2b-40e6-a2f2-7646ddec916a">

Eg. it could just show up on the left here on hover, so I don't have to click into the task to check it off.

**Comment by Jemoka** [comment]
oh yeah that's true but where should I put it

**Comment by Jemoka** [comment]
anywhere I've tried looked bad
